### PR TITLE
Initialize `theme` in localStorage if unset

### LINKED ISSUE #289: Initial switch to dark mode doesn't trigger theme change
### Summary

Dark mode can be enabled by clicking the light bulb icon at the top-right of the sidebar but, the first time you try, it actually requires *two* clicks for it to have an effect. Although the light theme's styles are used by default, the `theme` key isn't set in local storage until the first attempt to toggle dark mode... by which time it's too late.

To reproduce, delete the `theme` key from Local Storage and reload the page.

### Problem
The lack of a `theme` key only seems to be an issue because of this comparison in the `darkmode` plugin:

https://github.com/dshoreman/servidor/blob/37e18d472bb69f9ac9e745df98bef502a43ac3eb/resources/js/plugins/darkmode/index.js#L15-L18

When no `theme` key is defined, the value of `this.currentTheme` will be `null`, causing it to fall back to `'light'`.

### Solution

At first glance the easy option would be something like this, but it only reverses the issue:

```js
this.currentTheme = 'dark' === this.currentTheme ? 'light' : 'dark';
```

While it would correctly set dark mode when the theme is `null`, any invalid values would incorrectly fall back to the dark theme which could cause further issues when loading the actual stylesheets for the current theme.

Instead of inverting the comparison, we need to **set a default value with `localStorage.setItem('theme', 'light')`** at some point *before* the `toggleDarkMode()` method is called. The `themed-page` component is used everywhere, so that could be a good place to hook into a load/ready event and check if `['dark', 'light'].includes(this.currentTheme)`.

### PR DESCRIPTION
**Pull request by stoppert**
Inside the mixinx created hook we can check if the currentTheme is null (not set in localStorage) and then set it to the default value of 'light'

To my understanding this should always work as data should be fully initialized and reactive when the "created" hook is called.

Fixes #289

### CODE REVIEW

File: resources/js/plugins/darkmode/index.js [hunk 1]
```diff
@@ -1,6 +1,11 @@
 export default {
     install(vue) {
         vue.mixin({
+            created() {
+                if (this.currentTheme === null) {
```
Comment (dshoreman) [inline resources/js/plugins/darkmode/index.js:5]: This should be `null === this.currentTheme`, travis is blocking merge currently

File: resources/js/plugins/darkmode/index.js [hunk 2]
```diff
@@ -1,6 +1,11 @@
...
+                    localStorage.setItem('theme', this.currentTheme = 'light');
```
Comment (dshoreman) [inline resources/js/plugins/darkmode/index.js:6]: Suspect `this.currentTheme = 'light'` will cause errors too and needs to be defined separately on the line above

**Review by dshoreman — CHANGES_REQUESTED** [review]
Thanks! Good idea to use the created hook, much better than faffing about with global page/component events :laughing: 

Once travis is happy this'll be good to go. It stops at the first error so my second comment is a guess, but run `make kitchen-sink` from the project dir and it'll go through all the tests and linting bits to save having to commit/push/commit/etc

**Comment by stoppert** [comment]
How rude of travis

**Review by dshoreman — APPROVED** [review]
Perfect! Just tested locally and the light bulb even works as expected if I delete the `theme` key from local storage before I toggle the theme. Sorry it took so long to get back to this, will get it merged now :+1:
